### ISSUE TITLE
.data section cannot contain semicolons

### ISSUE THREAD

**Issue by radiofreejohn** [francisrstokes/16bitjs#18]
I think that the way `cleanup` trims out comments will make programs with semicolons in the data section fail to assemble, or assemble incorrectly.

**Comment by xlbadger** [comment]
Ah yes I see. The current method would prohibit you to use a semicolon in a text string. 

Without testing it, I believe that splitting comments on a `(?!\\;);.` regular expression would fix this, as long as semicolons are escaped in the string. Any better fix is going to require writing a much more complex parser which is a bit out of my scope for this project at the moment.

Ill give it a go this evening and see if it works.

**Comment by francisrstokes** [comment]
Ah yes I see. The current method would prohibit you to use a semicolon in a text string.

Without testing it, I believe that splitting comments on a (?!\\;);. regular expression would fix this, as long as semicolons are escaped in the string. Any better fix is going to require writing a much more complex parser which is a bit out of my scope for this project at the moment.

Ill give it a go this evening and see if it works.

**Comment by francisrstokes** [comment]
So with a little added complexity to the comment stripping functionality, https://github.com/francisrstokes/16bitjs/pull/20 should solve the issue.

Semicolons in data section need to be escaped in order to not be recognised as comments.
