### ISSUE TITLE
LDV16 B, value probably doesn't work

### ISSUE THREAD

**Issue by redfast00** [francisrstokes/16bitjs#22]
Hi, I really enjoyed your article and I am now doing a code-along (I read the specs on your blog post and try to implement them in Python). I just finished coding the LDV16 expander and when I looked at [your code](https://github.com/francisrstokes/16bitjs/blob/master/src/assembler/preprocessor/stages/pseudo-instructions/expanders/general/LDV16.js), I saw that the (temporary) B register was hardcoded, so setting the B register with LDV16 probably won't work as intended. I solved this like [this](https://github.com/redfast00/RCPU/blob/master/RCPU/assembler/expanders/utilexpander.py#L16)

**Comment by francisrstokes** [comment]
Hey there. Cool to see you're doing a code along, Python is a nice language and I'd love to see how that turns out! Anyway, you are correct - I'll apply the same fix that you did in your repo. Thanks for the heads up 😄
