### ISSUE TITLE
Extend LDR with offset mode

### ISSUE THREAD

**Issue by francisrstokes** [francisrstokes/16bitjs#27]
To make accessing data structures easier, `LDR` can take two additional arguments: `MODE` and `OFFSET_REGISTER`.

If `MODE` is 1, then `SOURCE` is treated as a base which is offset by the value in `OFFSET_REGISTER`.

**Comment by hlide** [comment]
I don't think it is necessary. Assembler issues `LDR` and `LDP` with `XXXXXXXX` being 0 currently so there is no reason to get a `MODE` for this purpose.

**Comment by francisrstokes** [comment]
So you're thinking just providing a 8-bit offset directly?

**Comment by hlide** [comment]
I suggest the following changes:

LDA -> LDA (no change)
LDM -> STA (LDM kept as pseudo for retro-compatibility)
LDR -> LDR (with optional offset defaulted to 0)
LDP -> STR (with optional offset defaulted to 0 and LDP kept as pseudo without offset for retro-compatibility)

the situation for `LDR`/`STR` is similar to `MVR`: `VVVVVVVV` being 0 is like having `MODE` set to 0 or else 1.

**Comment by francisrstokes** [comment]
I can get on board with all of those actually. By `STM` I guess you mean the currently named `LDM`?

OK, so let's close this issue and create one for each change so they can be incrementally implemented.
