### ISSUE TITLE
Use debugger for ASCII ART

### ISSUE THREAD

**Issue by miselaytes-anton** [francisrstokes/16bitjs#3]
Can we put something in memory in a way that when dumped it looks like a [giraffe](https://en.wikipedia.org/wiki/Talk:Giraffe)?
p.s.:
<img width="876" alt="screen shot 2017-07-12 at 08 27 40" src="https://user-images.githubusercontent.com/5480808/28104577-16bbff48-66dc-11e7-8685-3b47b9867bd9.png">

**Comment by francisrstokes** [comment]
I believe https://github.com/francisrstokes/16bitjs/blob/master/asm/giraffe.asm fixes this issue?
