### ISSUE TITLE
Merge SYS, HLT and RET since they no arguments

### ISSUE THREAD

**Issue by hlide** [francisrstokes/16bitjs#30]
Those three instructions have only the 4-bit main opcode considered and no other relevant fields. Instead of having three different main opcode, we can have only one and used some X bits to carry the real opcode for SYS, HLT and RET and be able to add other possible instructions where no SS and DD are needed. As for SYS, I would have considered an immediate (8-bit ?) value to encode the system call code instead of relying on a register value (I believe it is A currently) .  Two main opcodes would be freed for other usages that I can have in mind.

**Comment by redfast00** [comment]
Over at https://github.com/redfast00/RCPU (a similar project in Python with instructions inspired by 16bitjs), I simply push the syscall number onto the stack, along with arguments, and place return values on the stack as well. The SYS instruction then pop's and pushes onto the stack.

**Comment by francisrstokes** [comment]
@hlide I agree that these instructions can be merged. What would you name this common instruction? Also as a side note, if you want to implement this feature and a rewrite of LDV, please keep make them in separate pull requests.

@redfast00 ah that's also a nice way to do it. I was going for a similar kind of approach to to x86 0x80 interrupt (https://en.wikibooks.org/wiki/X86_Assembly/Interfacing_with_Linux), which basically has the registers set up with arguments. I don't think this needs to be changed to be honest, but there are definitely a bunch of different ways you could do it.

**Comment by redfast00** [comment]
@francisrstokes it does indeed not have to be changed, I think it works the way it is. Sorry for hijacking this issue, but is there a roadmap of things to do? Don't have time for it now (working on RCPU), but I'd love to contribute in the future.

**Comment by francisrstokes** [comment]
@redfast00 no worries. I'm starting to use the git issues with enhancement tags to create extension proposals. Discussion can take place in the issues (like this one). I've created a CONTRIBUTING.md file repo that kind of lays out the main ideas with creating proposals. Your project is looking great by the way, it's really coming along!
