### ISSUE TITLE
MOV - using the upper 8 bits to store a sign-extended immediate as an addend

### ISSUE THREAD

**Issue by hlide** [francisrstokes/16bitjs#33]
# Proposal

## Instruction MOV
MOV is renamed as MVR and MOV, DEC, and INC become pseudos using MVR

### Before:
|`MOV`| `D, S`          | `XXXXXXXXSSDD0000` | Move value at source register to destination register|

### After:
|`MVR`| `D, S, V`          | `VVVVVVVVSSDD0000` | Add sign-extended immediate value to value at source register and move it to destination register|
|`MOV`| `D, S`          | `00000000SSDD0000` | Move value at source register to destination register|
|`INC`| `D`          | `00000001DDDD0000` | Increment value at destination register|
|`DEC`| `D`          | `11111111DDDD0000` | Decrement value at destination register|

Retro-compatibility is kept for assembly code, not for machine code.

**Comment by hlide** [comment]
Rationale: `MVR D, S, V` executes `D <- sext16(S) + sext8(V)`.

**Comment by francisrstokes** [comment]
Merged proposal to master
