### ISSUE TITLE
Rename LDP to STR with an optional 8 bit offset

### ISSUE THREAD

**Issue by francisrstokes** [francisrstokes/16bitjs#37]
`LoaD into memory through Pointer` becomes `SToRe`.
Allow for an 8 bit offset for storing within a data structure.

Create a pseudo instruction `LDP` for compatibility.

**Comment by hlide** [comment]
Implementation available in branch proposal-37-STR.

**Comment by francisrstokes** [comment]
Hey - can you make pull requests from your repo to mine? Then I'll merge up :smile:

**Comment by hlide** [comment]
Sorry but I have 3 branches and I fail to find how to create a clean pull request for each (they are not including only one commit) and they appear to lead to a benign conflict.

**Comment by francisrstokes** [comment]
Hey, no problem. I think I can see what's going on here.

Your pull requests are always relative to my master branch since my repo is considered the 'upstream'. You need to get in sync with the master branch of my repository before you can push more features (otherwise there will be merge conflicts).

So for instance I can see that you're actually not creating feature branches, only commits in your master branch. When you make a pull request, that request is based on a particular branch. The idea here is that you have an up to date master branch, and you branch off from that with each feature. That feature should only contain a single change (proposal #36) for instance. Then when you come to implement the next feature, you checkout master again, and create yet another feature branch. Each branch gets it's own pull request. I hope that makes sense, also as to why it's worth doing things this way.

To get concrete, on your fork, you should first `git pull upstream master`. That will get the latest changes. After that you can `git checkout -b feature/proposal-xyz`. There you can make your changes for that proposal, and then `git push origin feature/proposal-xyz`. If you the 16bitjs github page after that, you'll see a button that says something like "you just push, create pull request".

**Comment by hlide** [comment]
Seriously, I think those 3 issues should have been in one issue because they have some inter-dependency in fact (you cannot break the orthogonality between those instructions by splitting them)  and now it drives me nuts because of generated conflicts due to mix of past/future commits - have a look upon one of my conflicting PR.

**Comment by francisrstokes** [comment]
In the case where you cannot break the issue into the smallest pieces I'd say yes, but it should be the aim as much as possible. OK I've resolved the merge conflicts in line, and merged. 

Don't worry about the git stuff too much, I appreciate your input on the project - you've brought in some really valuable contributions.
