### ISSUE TITLE
LDA/LDM/LDR/LDP become LDA/STA/LDR/STR

### ISSUE THREAD

**Issue by hlide** [francisrstokes/16bitjs#40]
Those are instructions from Load Store Unit (LSU) and as such must be handled as an entity here.

So #35, #36, and #37 are implemented together through this issue.

See #35 for LDR details
See #36 for STA details
See #37 for STR details

**Comment by francisrstokes** [comment]
What is LSU?

**Comment by hlide** [comment]
in a 32-bit RISC CPU for instance, there are 4 main components:
- ALU: Arithmetic/Logical Unit (32 ¤ 32 -> 32 with no latency)
- MDU: Multiply/Divide Unit (32 * 32 -> 64, 64 + 32 * 32 -> 64, 32 ¤ 32 -> 32 with long latency)  
- LSU: Load/Store Unit
- BCU: Branch Control Unit

**Comment by francisrstokes** [comment]
OK this is why I think the discussion phase of a proposal is quite important. It's nice to be on the same page about a potential implementation. I'm assuming here then that you want to add a module (lsu.js) to the cpu. In that module you'll handle all load/store based instructions directly. Is that correct?

**Comment by hlide** [comment]
I was coining the term LSU from hardware viewpoint, not from software viewpoint. So there is no such lsu.js. But I found weird to make the offset adoption for LDR and STR separately as features because in hardware the computation of an effective address is done by the same hardware instance. I saw you finally integrate one of my three implementations. I was in the process to make them in one PR to keep coherency .

**Comment by francisrstokes** [comment]
I see where the miscommunication took place. This is a software project, and I really do believe it's important to implement every piece individually. Each instruction can be rewritten in isolation, and so it should be . You can imagine the situation where we split those 3 issues between us and I wrote one and you wrote one. That's only possible when you isolate features. It's also a lot easier to review code when it only touches a single concept. I understand your reasoning, but I believe this is how features should be implemented.

**Comment by hlide** [comment]
Anyway, things in my repository went awry so I've  just added the two remaining PRs as such. I need to fix the mess in my repository when all those PRs are done.

**Comment by francisrstokes** [comment]
Hey I resolved all the merge conflicts and merged the pull requests so all of these steps are in place.  It was quite a bit of work because like you say - the repos got pretty haywire. For future enhancements let's chat about the least conflicting workflow first to avoid the same again, but overall awesome! Thanks 😄
