### ISSUE TITLE
Missing ESLint configuration

### ISSUE THREAD

**Issue by tetsuo** [francisrstokes/16bitjs#52]
Hello @francisrstokes,

This is a very interesting project, thanks! greatly inspired me to read about some theory this weekend.

I want to contribute as well but the ESLint configuration file is missing in the repository. What is the policy on this? :)

Cheers!

**Comment by francisrstokes** [comment]
Thanks, glad it's interesting! I've added the eslint that I'm working from into the project.

**Comment by francisrstokes** [comment]
However you'll probably find some thing's are not completely linted. I haven't tuned the config to the coding style exactly 😄 That would be nice to do though for sure. The coding style of the project is pretty consistent, and the main linter complaints are things that in this project at least should be warnings at most, or disabled on a per line or per file basis.
